name: Manual Contribution
on:
  workflow_dispatch: # Isse "Run workflow" button show hoga

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create or Update Contribution File
        run: |
          # File mein current timestamp likh kar update karein
          echo "Contribution record: $(date)" >> activity.log
          
          # Git configuration
          git config user.name "Tehseen-webdeveloper"
          git config user.email "tahseen.test@gmail.com"
          
          # Changes stage aur commit karein
          git add activity.log
          git commit -m "feat: update project activity log"
          
          # Push changes
          git push