name: Manual Contribution

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Enter Date (YYYY-MM-DD)'
        required: true
        default: '2026-05-22'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Past Commit
        run: |
          DATE_INPUT="${{ github.event.inputs.date }}"
          echo "Contribution for $DATE_INPUT" >> manual_log.txt
          
          git config user.name "Tehseen-webdeveloper"
          git config user.email "tahseen.test@gmail.com"
          git add manual_log.txt
          
          # Force date
          GIT_AUTHOR_DATE="$DATE_INPUT 12:00:00" GIT_COMMITTER_DATE="$DATE_INPUT 12:00:00" git commit -m "contribution: $DATE_INPUT"
          git push