name: Manual Commit

on:
  workflow_dispatch: # Ye button activate karta hai

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Update file
        run: |
          echo "Manual contribution - $(date)" >> contribution.txt
          git config user.name "Tehseen-webdeveloper"
          git config user.email "tahseen.test@gmail.com"
          git add contribution.txt
          git commit -m "Manual contribution"
          git push